# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@1
  displayName: 'Use .NET Core sdk 3.1.1'
  inputs:
    version: 3.1.100
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:    
    command: publish
    projects: '*.sln'
    noCache: true
    arguments: '--configuration Release --output "$(build.artifactstagingdirectory)"'
    modifyOutputPath: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
